server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

logging:
  level:
    root: WARN
    com.marketdata: INFO

marketdata:
  provider:
    alpha-vantage:
      base-url: https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol=
      api-key: ${ALPHAVANTAGE_API_KEY}
