server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VHOST:/}
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

logging:
  level:
    root: WARN
    com.marketdata: INFO

marketdata:
  provider:
    alpha-vantage:
      base-url: https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol=
      api-key: ${ALPHAVANTAGE_API_KEY}
    brapi:
      base-url: https://brapi.dev/api/quote/
      api-key: ${BRAPI_API_KEY}
